server:
  port: 8081

spring:
  application:
    name: auth-service

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: https://dev-acun87tlm2zqnkn3.us.auth0.com/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka