server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: food-service
              uri: lb://FOOD-SERVICE
              predicates:
                - Path=/foods/**

            - id: review-service
              uri: lb://REVIEW-SERVICE
              predicates:
                - Path=/reviews/**

            - id: favorite-service
              uri: lb://FAVORITE-SERVICE
              predicates:
                - Path=/favorites/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka