server:
  port: 8083

spring:
  application:
    name: review-service

  datasource:
    url: jdbc:mysql://localhost:3306/foodhunt_review_service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis
    redis:
      time-to-live: 10m

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: https://dev-acun87tlm2zqnkn3.us.auth0.com/

logging:
  level:
    org.springframework.cache: TRACE
    org.springframework.data.redis.cache: TRACE
    org.springframework.data.redis.core: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka